// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xymvctcyuaspuwjfswmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bXZjdGN5dWFzcHV3amZzd210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTYzODAsImV4cCI6MjA2NDEzMjM4MH0.KX8RoBaHxQ-b4k8WVcj0RG_sx-HMxc18V0jKwl3Yz_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);